# Nesse Ci buildamos o nosso arquivo Dockerfile, logamos no site da dockerhub>myaccount>security>new acces token e subimos a nossa imagem para la. O password nada mais é que um token gerado na docker hub. Colocamos esses dados sensiveis(username e token) no github>repositorio>Secrets and variables>actions>Repository secrets>NAME_DA_SECRET
# Generate sha é o sha_code do commit, pegamos ele e colocamos somente os 7 primeiro caracteres como tag da imagem do docker e damos um push na mesma imagem mas sempre como latest, para que tenhamos sempre o acompanhamento das imagens por sha do commit e repetimos a ultima imagem enviada como latest para saber que ela foi a ultima enviada para o docker hub
# O run é quando fazemos o comando na unha, o uses é quando ja existe ele pronto,  runs-on SO que vai ficar a nossa imagem
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t pedroperipecias/learn-to-use-docker:${{ steps.generate_sha.outputs.sha }} .
      
      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push image
        run: |
          docker push pedroperipecias/learn-to-use-docker:${{ steps.generate_sha.outputs.sha }}
          docker tag pedroperipecias/learn-to-use-docker:${{ steps.generate_sha.outputs.sha }} pedroperipecias/learn-to-use-docker:latest
          docker push pedroperipecias/learn-to-use-docker:latest